### PR TITLE
Create ErrorCodes1.0.0.4.json

### PR DESCRIPTION
**Pull request by GsmHack4you**
contact whatsapp +31617965814 discord:gsmhack4you email:gsmhack4you@gmail.com

### CODE REVIEW

**Comment by amoamare** [comment]
whats up

**Comment by GsmHack4you** [comment]
these are my first steps on github and I'm not entirely good at updating
your project, so just to be sure, I'll send you my findings in the
attachment, I've corrected some of the errors and added additional
information found on the internet, and I've confirmed some of the errors. The
GDDR6 memory chip numbers added should be read from 1 to 8 as follows [1]
[2] [3] [4] [8] [7] [6] [5] having the power section on the right side
additional
observations: short circuits start (in the cases I had) from 808 809,
perhaps there is a pattern in this syscon does not log errors if there is
no communication with the BIOS chip update error SU-101312-8 (no drive
communicating with drive logic) is not logged by syscon Gddr6 Vram errors
manifested by artifacts (CE-108225-1 and application shutdown) are not
recorded by syscon GDDR6 errors recorded by syscon only concern lack of
data integrity and faulty communication, but their absence does not exclude
damage to the VRAM chips

pt., 22 gru 2023 o 00:46 amoamare ***@***.***> napisał(a):

**Comment by GsmHack4you** [comment]
[image: image.png]

pt., 22 gru 2023 o 00:46 amoamare ***@***.***> napisał(a):

**Comment by GsmHack4you** [comment]
obraz_2023-12-22_011739620
[ErrorCodes1.0.0.4.json](https://github.com/amoamare/PS5CodeReader/files/13747043/ErrorCodes1.0.0.4.json)

**Pull request closed without merging**
